export const COLLEGES_OF_EDUCATION = [
    "Adeyemi College of Education, Ondo",
    "African Thinkers Community of Inquiry College of Education, Enugu",
    "Akwa Ibom State College of Education, Afaha-Nsit",
    "Alvan Ikoku Federal College of Education, Owerri",
    "Aminu Kano College of Education, Kano",
    "Angel Michel College of Education, Makurdi",
    "Ansar-Ud-Deen College of Education, Isolo",
    "College of Education, Agbor",
    "College of Education, Akwanga",
    "College of Education, Ankpa",
    "College of Education, Azare",
    "College of Education, Ekiadolor-Benin",
    "College of Education, Gindiri",
    "College of Education, Hong",
    "College of Education, Ikere-Ekiti",
    "College of Education, Katsina-Ala",
    "College of Education, Lanlate",
    "College of Education, Minna",
    "College of Education, Oju",
    "College of Education, Warri",
    "College of Education, Zing",
    "Cornerstone College of Education, Lagos",
    "Cross River State College of Education, Akamkpa",
    "Delar College of Education, Ibadan",
    "Delta State College of Physical Education, Mosogar",
    "Diamond College of Education, Aba",
    "Ebonyi State College of Education, Ikwo",
    "Emmanuel Alayande College of Education, Oyo",
    "Federal College of Education (Special), Oyo",
    "Federal College of Education (Technical), Akoka",
    "Federal College of Education (Technical), Asaba",
    "Federal College of Education (Technical), Bichi",
    "Federal College of Education (Technical), Gombe",
    "Federal College of Education (Technical), Gusau",
    "Federal College of Education (Technical), Omoku",
    "Federal College of Education (Technical), Potiskum",
    "Federal College of Education (Technical), Umunze",
    "Federal College of Education, Abeokuta",
    "Federal College of Education, Eha-Amufu",
    "Federal College of Education, Kano",
    "Federal College of Education, Katsina",
    "Federal College of Education, Kontagora",
    "Federal College of Education, Obudu",
    "Federal College of Education, Okene",
    "Federal College of Education, Pankshin",
    "Federal College of Education, Yola",
    "Federal College of Education, Zaria",
    "FCT College of Education, Zuba",
    "Jigawa State College of Education, Gumel",
    "Kaduna State College of Education, Gidan Waya",
    "Kano State College of Education, Kano",
    "Kashim Ibrahim College of Education, Maiduguri",
    "Katsina State College of Education, Katsina",
    "Kebbi State College of Education, Argungu",
    "Kinsey College of Education, Ilorin",
    "Kogi State College of Education, Ankpa",
    "Kwara State College of Education, Ilorin",
    "Kwara State College of Education, Oro",
    "Lagos State College of Primary Education, Noforija",
    "Michael Otedola College of Primary Education, Noforija",
    "Muftau Lanihun College of Education, Ibadan",
    "Nasarawa State College of Education, Akwanga",
    "Niger State College of Education, Minna",
    "Nwafor Orizu College of Education, Nsugbe",
    "Ogun State College of Education, Ijebu-Ode",
    "Osun State College of Education, Ila-Orangun",
    "Osun State College of Education, Ilesa",
    "Peaceland College of Education, Enugu",
    "Plateau State College of Education, Gindiri",
    "Rivers State College of Education, Port Harcourt",
    "Saadatu Rimi College of Education, Kumbotso",
    "Shehu Shagari College of Education, Sokoto",
    "St. Augustine College of Education, Akoka",
    "Tai Solarin College of Education, Omu-Ijebu",
    "Umar Ibn Ibrahim El-Kanemi College of Education, Bama",
    "Zamfara State College of Education, Maru"
];
