export const INNOVATION_ENTERPRISE_INSTITUTIONS = [
    "Afrihub ICT Institute, Abuja",
    "Ambassador College of Management and Technology, Port Harcourt",
    "Buckingham Academy of Management and Technology, Ogidi",
    "Center for Creative Arts Education, Port Harcourt",
    "City Gate Institute of Innovation and Technology, Ibadan",
    "Complete Computers and Technology Institute, Benin City",
    "Dalewares Institute of Technology, Lagos",
    "Dialogue Computer Institute, Kaduna",
    "Digital Bridge Institute, Abuja",
    "Emdee Shipping and Maritime College, Apapa",
    "Friskel Divinity College, Gariki",
    "Global Maritime Academy, Ogoni",
    "Highland College of Technology and Further Education, Ibadan",
    "Ibadan City Polytechnic, Ibadan",
    "Imfi Academy, Uyo",
    "KarRox Processor, Ogba",
    "Lagos Aviation and Maritime Business Academy, Iba",
    "Lineo School of Media and Design, Lagos",
    "Mario Institute of Hospitality Management and Entrepreneurship Education, Nsukka",
    "Marvel Institute of Management and Technology, Kuchikau",
    "Maurid Institute of Management and Technology, Oron",
    "NIIT Education and Training Centre, Ikeja",
    "Offer Centre Institute of Agriculture, Oluponna",
    "Olawoyin School of Innovative Studies, Ibadan",
    "Pefti Film Institute, Lagos",
    "Prime Innovation Institute of Technology, Ajah",
    "Risk Control Academy, Lagos",
    "Rolof Computer Academy, Warri",
    "School of Banking Honours, Lagos",
    "Southern Nigerian Institute of Innovative Technology, Owerri",
    "Stars Maritime Academy, Iju",
    "Total Human Capital Development Institute, Lagos",
    "Tower Polytechnic, Ibadan",
    "Unival Institute of Technology, Benin City",
    "Upskill Digital Institute, Lagos",
    "Yenagoa Enterprise School, Yenagoa"
];
