export const POLYTECHNICS = [
    "Abdu Gusau Polytechnic, Talata Mafara",
    "Abia State Polytechnic, Aba",
    "Abraham Adesanya Polytechnic, Ijebu-Igbo",
    "Abubakar Tatari Ali Polytechnic, Bauchi",
    "Adamawa State Polytechnic, Yola",
    "Akanu Ibiam Federal Polytechnic, Unwana",
    "Akwa Ibom State Polytechnic, Ikot Osurua",
    "Alovera Polytechnic, Ota",
    "Auchi Polytechnic, Auchi",
    "Benue State Polytechnic, Ugbokolo",
    "Binyaminu Usman Polytechnic, Hadejia",
    "Bolmor Polytechnic, Ibadan",
    "Delta State Polytechnic, Ogwashi-Uku",
    "Delta State Polytechnic, Otefe-Oghara",
    "Delta State Polytechnic, Ozoro",
    "Dorben Polytechnic, Abuja",
    "Eastern Polytechnic, Port Harcourt",
    "Edo State Institute of Technology and Management, Usen",
    "Federal Polytechnic, Ado-Ekiti",
    "Federal Polytechnic, Bali",
    "Federal Polytechnic, Bauchi",
    "Federal Polytechnic, Bida",
    "Federal Polytechnic, Damaturu",
    "Federal Polytechnic, Ede",
    "Federal Polytechnic, Ekowe",
    "Federal Polytechnic, Idah",
    "Federal Polytechnic, Ilaro",
    "Federal Polytechnic, Ile-Oluji",
    "Federal Polytechnic, Kaura Namoda",
    "Federal Polytechnic, Mubi",
    "Federal Polytechnic, Nasarawa",
    "Federal Polytechnic, Nekede",
    "Federal Polytechnic, Offa",
    "Federal Polytechnic, Oko",
    "Federal Polytechnic, Ukana",
    "Fidei Polytechnic, Gboko",
    "Gateway Polytechnic, Saapade",
    "Grace Polytechnic, Surulere",
    "Hassan Usman Katsina Polytechnic, Katsina",
    "Heritage Polytechnic, Eket",
    "Hussaini Adamu Federal Polytechnic, Kazaure",
    "Ibarapa Polytechnic, Eruwa",
    "Igbajo Polytechnic, Igbajo",
    "Institute of Management and Technology, Enugu",
    "Interlink Polytechnic, Ijebu-Jesa",
    "Jigawa State Polytechnic, Dutse",
    "Kaduna Polytechnic, Kaduna",
    "Kano State Polytechnic, Kano",
    "Kings Polytechnic, Ubiaja",
    "Kogi State Polytechnic, Lokoja",
    "Kwara State Polytechnic, Ilorin",
    "Lagos City Polytechnic, Ikeja",
    "Lagos State Polytechnic, Ikorodu",
    "Light House Polytechnic, Evbuobanosa",
    "Mai Idris Alooma Polytechnic, Geidam",
    "Moshood Abiola Polytechnic, Abeokuta",
    "Nasarawa State Polytechnic, Lafia",
    "Niger State Polytechnic, Zungeru",
    "Nuhu Bamalli Polytechnic, Zaria",
    "Ogun State Institute of Technology, Igbesa",
    "Oke-Ogun Polytechnic, Saki",
    "Osun State Polytechnic, Iree",
    "Plateau State Polytechnic, Barkin Ladi",
    "Polytechnic of Sokoto State, Sokoto",
    "Ramat Polytechnic, Maiduguri",
    "Rivers State Polytechnic, Bori",
    "Ronik Polytechnic, Ejigbo",
    "Rufus Giwa Polytechnic, Owo",
    "Shaka Polytechnic, Benin City",
    "Temple Gate Polytechnic, Aba",
    "The Polytechnic, Ibadan",
    "Tower Polytechnic, Ibadan",
    "Waziri Umaru Federal Polytechnic, Birnin Kebbi",
    "Wolex Polytechnic, Iyana Ipaja",
    "Yaba College of Technology, Yaba",
    "Zamfara State Polytechnic, Talata Mafara"
];
