export const INSTITUTION_TYPES = [
    "UNIVERSITIES AND OTHER DEGREE-AWARDING INSTITUTIONS",
    "COLLEGES OF EDUCATION",
    "POLYTECHNICS AND MONOTECHNICS",
    "INNOVATION ENTERPRISE INSTITUTIONS"
];
