export const UNIVERSITIES = [
    "Abia State University, Uturu",
    "Abubakar Tafawa Balewa University, Bauchi",
    "Achievers University, Owo",
    "Adamawa State University, Mubi",
    "Adekunle Ajasin University, Akungba-Akoko",
    "Adeleke University, Ede",
    "Afe Babalola University, Ado-Ekiti",
    "African University of Science and Technology, Abuja",
    "Ahmadu Bello University, Zaria",
    "Ajayi Crowther University, Oyo",
    "Akwa Ibom State University, Ikot-Akpaden",
    "Alex Ekwueme Federal University, Ndufu-Alike",
    "Al-Hikmah University, Ilorin",
    "Al-Qalam University, Katsina",
    "Ambrose Alli University, Ekpoma",
    "American University of Nigeria, Yola",
    "Anchor University, Lagos",
    "Arthur Jarvis University, Akpabuyo",
    "Atiba University, Oyo",
    "Augustine University, Ilara",
    "Babcock University, Ilishan-Remo",
    "Bamidele Olumilua University of Education, Science and Technology, Ikere-Ekiti",
    "Bauchi State University, Gadau",
    "Bayero University, Kano",
    "Baze University, Abuja",
    "Bell University of Technology, Ota",
    "Benson Idahosa University, Benin City",
    "Benue State University, Makurdi",
    "Bingham University, Karu",
    "Borno State University, Maiduguri",
    "Bowen University, Iwo",
    "Caleb University, Imota",
    "Caritas University, Amorji-Nike",
    "Chrisland University, Owode",
    "Christopher University, Mowe",
    "Chukwuemeka Odumegwu Ojukwu University, Uli",
    "Clifford University, Owerrinta",
    "Coal City University, Enugu",
    "Covenant University, Ota",
    "Crawford University, Igbesa",
    "Crescent University, Abeokuta",
    "Cross River University of Technology, Calabar",
    "Crown Hill University, Eiyenkorin",
    "Delta State University, Abraka",
    "Dominican University, Ibadan",
    "Ebonyi State University, Abakaliki",
    "Edo State University, Uzairue",
    "Edwin Clark University, Kiagbodo",
    "Ekiti State University, Ado-Ekiti",
    "Eko University of Medicine and Health Sciences, Ijanikin",
    "Elizade University, Ilara-Mokin",
    "Enugu State University of Science and Technology, Enugu",
    "Evangel University, Akaeze",
    "Federal University of Agriculture, Abeokuta",
    "Federal University of Petroleum Resources, Effurun",
    "Federal University of Technology, Akure",
    "Federal University of Technology, Minna",
    "Federal University of Technology, Owerri",
    "Federal University, Birnin Kebbi",
    "Federal University, Dutse",
    "Federal University, Dutsin-Ma",
    "Federal University, Gashua",
    "Federal University, Gusau",
    "Federal University, Kashere",
    "Federal University, Lafia",
    "Federal University, Lokoja",
    "Federal University, Otuoke",
    "Federal University, Oye-Ekiti",
    "Federal University, Wukari",
    "Fountain University, Osogbo",
    "Godfrey Okoye University, Ugwuomu-Nike",
    "Gombe State University, Gombe",
    "Gregory University, Uturu",
    "Hallmark University, Ijebu-Itele",
    "Hezekiah University, Umudi",
    "Ibrahim Badamasi Babangida University, Lapai",
    "Igbinedion University, Okada",
    "Ignatius Ajuru University of Education, Port Harcourt",
    "Imo State University, Owerri",
    "Joseph Ayo Babalola University, Ikeji-Arakeji",
    "Kaduna State University, Kaduna",
    "Kano University of Science and Technology, Wudil",
    "Kebbi State University of Science and Technology, Aliero",
    "Kings University, Ode-Omu",
    "Kogi State University, Anyigba",
    "Kola Daisi University, Ibadan",
    "Kwara State University, Malete",
    "Kwararafa University, Wukari",
    "Ladoke Akintola University of Technology, Ogbomoso",
    "Lagos State University, Ojo",
    "Landmark University, Omu-Aran",
    "Lead City University, Ibadan",
    "Legacy University, Okija",
    "Madonna University, Elele",
    "McPherson University, Seriki Sotayo",
    "Michael and Cecilia Ibru University, Agbarha-Otor",
    "Michael Okpara University of Agriculture, Umudike",
    "Modibbo Adama University of Technology, Yola",
    "Mountain Top University, Makogi Oba",
    "Nasarawa State University, Keffi",
    "National Open University of Nigeria",
    "Niger Delta University, Wilberforce Island",
    "Nile University of Nigeria, Abuja",
    "Nnamdi Azikiwe University, Awka",
    "Novena University, Ogume",
    "Obafemi Awolowo University, Ile-Ife",
    "Obong University, Obong Ntak",
    "Oduduwa University, Ipetumodu",
    "Olabisi Onabanjo University, Ago-Iwoye",
    "Ondo State University of Science and Technology, Okitipupa",
    "Osun State University, Osogbo",
    "Pan-Atlantic University, Lagos",
    "Paul University, Awka",
    "Plateau State University, Bokkos",
    "Polaaku University of Science and Technology",
    "Precious Cornerstone University, Ibadan",
    "Redeemer's University, Ede",
    "Renaissance University, Ugbawka",
    "Rhema University, Aba",
    "Ritman University, Ikot Ekpene",
    "Rivers State University, Port Harcourt",
    "Salem University, Lokoja",
    "Samuel Adegboyega University, Ogwa",
    "Skyline University Nigeria, Kano",
    "Sokoto State University, Sokoto",
    "Southwestern University, Okun-Owa",
    "Spiritan University, Nneochi",
    "Summit University, Offa",
    "Tai Solarin University of Education, Ijagun",
    "Tansian University, Umunya",
    "Taraba State University, Jalingo",
    "The Technical University, Ibadan",
    "Umaru Musa Yar'adua University, Katsina",
    "University of Abuja, Abuja",
    "University of Africa, Toru-Orua",
    "University of Agriculture and Environmental Sciences, Umuagwo",
    "University of Benin, Benin City",
    "University of Calabar, Calabar",
    "University of Ibadan, Ibadan",
    "University of Ilorin, Ilorin",
    "University of Jos, Jos",
    "University of Lagos, Lagos",
    "University of Maiduguri, Maiduguri",
    "University of Medical Sciences, Ondo",
    "University of Nigeria, Nsukka",
    "University of Port Harcourt, Port Harcourt",
    "University of Uyo, Uyo",
    "Usman Danfodio University, Sokoto",
    "Veritas University, Abuja",
    "Wellspring University, Benin City",
    "Wesley University, Ondo",
    "Western Delta University, Oghara",
    "Yobe State University, Damaturu",
    "Yusuf Maitama Sule University, Kano",
    "Zamfara State University, Talata Mafara"
];
