import { Tool, Type } from "@google/genai";

// Environment-aware Model Configuration
// Allows switching models via environment variables without code changes
export const LIVE_MODEL = process.env.REACT_APP_GEMINI_LIVE_MODEL || process.env.NEXT_PUBLIC_GEMINI_LIVE_MODEL || 'gemini-2.5-flash-native-audio-preview-12-2025';

// Placeholder for Economy/Low-Tier users (e.g. Lower cost, slightly different latency profile)
export const LIVE_MODEL_ECONOMY = process.env.REACT_APP_GEMINI_LIVE_MODEL_ECONOMY || process.env.NEXT_PUBLIC_GEMINI_LIVE_MODEL_ECONOMY || 'gemini-2.0-flash-exp';

export const CHAT_MODEL = process.env.REACT_APP_GEMINI_CHAT_MODEL || process.env.NEXT_PUBLIC_GEMINI_CHAT_MODEL || 'gemini-2.5-flash';

// Define the tools
export const TOOLS: Tool[] = [
  {
    functionDeclarations: [
      {
        name: 'display_content',
        description: 'Display a word, sentence, or phonetic symbol on the student screen for them to pronounce. Use this whenever you ask the student to say something.',
        parameters: {
          type: Type.OBJECT,
          properties: {
            text: {
              type: Type.STRING,
              description: 'The content to display (e.g., "Sovereignty", "/ə/", "The cat sat on the mat").',
            },
            title: {
              type: Type.STRING,
              description: 'A label for the content (e.g., "Pronounce this word", "Phonetic Symbol", "Tongue Twister").',
            },
          },
          required: ['text'],
        },
      },
      {
        name: 'end_session',
        description: 'Ends the voice session. Call this tool immediately when you say goodbye, farewell, or when the user indicates they want to stop, regardless of the language used.',
        parameters: {
          type: Type.OBJECT,
          properties: {},
        },
      },
    ],
  },
];

// Fallback instruction if context generation fails
export const SYSTEM_INSTRUCTION = `
You are Raven, an AI Tutor for JAMB preparation.
Focus on Oral English pronunciation.
Always use the display_content tool to show words before asking the student to pronounce them.
If the conversation is ending, call the end_session tool.
`;

export const NIGERIAN_STATES = [
    'Abia', 'Adamawa', 'Akwa Ibom', 'Anambra', 'Bauchi', 'Bayelsa', 'Benue', 'Borno', 
    'Cross River', 'Delta', 'Ebonyi', 'Edo', 'Ekiti', 'Enugu', 'FCT', 'Gombe', 'Imo', 
    'Jigawa', 'Kaduna', 'Kano', 'Katsina', 'Kebbi', 'Kogi', 'Kwara', 'Lagos', 'Nasarawa', 
    'Niger', 'Ogun', 'Ondo', 'Osun', 'Oyo', 'Plateau', 'Rivers', 'Sokoto', 'Taraba', 
    'Yobe', 'Zamfara'
];

export const MONTHS = [
    'January', 'February', 'March', 'April', 'May', 'June', 
    'July', 'August', 'September', 'October', 'November', 'December'
];

// Generate years from 1980 to 2015
export const YEARS = Array.from({ length: 36 }, (_, i) => (2015 - i).toString());

export const SECONDARY_CLASSES = ['SSS 1', 'SSS 2', 'SSS 3'];
export const ATTEMPT_OPTIONS = ['1st attempt', '2nd attempt', '3rd attempt or more'];

export const NIGERIAN_BANKS = [
    'Access Bank',
    'Fidelity Bank',
    'First Bank of Nigeria',
    'First City Monument Bank (FCMB)',
    'Guaranty Trust Bank (GTBank)',
    'Heritage Bank',
    'Jaiz Bank',
    'Keystone Bank',
    'Kuda Bank',
    'Moniepoint',
    'Opay',
    'Palmpay',
    'Polaris Bank',
    'Providus Bank',
    'Stanbic IBTC Bank',
    'Standard Chartered Bank',
    'Sterling Bank',
    'SunTrust Bank',
    'Union Bank of Nigeria',
    'United Bank for Africa (UBA)',
    'Unity Bank',
    'Wema Bank',
    'Zenith Bank'
];

export const ALL_SUBJECTS = [
    'Agriculture Science',
    'Arabic',
    'Art',
    'Biology',
    'Chemistry',
    'Christian Religious Studies',
    'Commerce',
    'Computer Studies',
    'Economics',
    'French',
    'Geography',
    'Government',
    'Hausa',
    'History',
    'Home Economics',
    'Igbo',
    'Islamic Studies',
    'Literature-In-English',
    'Mathematics',
    'Music',
    'Physics',
    'Physical and Health Education',
    'Principles of Accounts',
    'Use of English',
    'Yoruba'
];

export const CATEGORIES = [
    { value: 'Science', label: 'Science', icon: '🔬', color: 'bg-palm-100 text-palm-700' },
    { value: 'Arts', label: 'Arts', icon: '📖', color: 'bg-indigo-100 text-indigo-700' },
    { value: 'Commercial', label: 'Commercial', icon: '💼', color: 'bg-earth-100 text-earth-700' }
];

export const FACULTIES = [
  {
    name: "Administration",
    courses: [
      "Accountancy / Accounting",
      "Actuarial Science",
      "Banking and Finance",
      "Business Administration",
      "Business Management",
      "Cooperative Economics and Management",
      "Human Resources Management",
      "Industrial Relations and Personnel Management",
      "Insurance",
      "International Relations",
      "Local Government Studies",
      "Marketing",
      "Office Technology and Management",
      "Public Administration",
      "Secretarial Administration",
      "Taxation"
    ]
  },
  {
    name: "Agriculture",
    courses: [
      "Agricultural Economics",
      "Agricultural Extension and Rural Development",
      "Agriculture",
      "Agronomy",
      "Animal Production and Health Services",
      "Animal Science",
      "Crop Production",
      "Crop Science",
      "Fisheries",
      "Food Science and Technology",
      "Forestry and Wildlife Management",
      "Home Science and Management",
      "Hotel Management and Tourism",
      "Soil Science"
    ]
  },
  {
    name: "Arts / Humanities",
    courses: [
      "African Languages and Literature",
      "Arabic Studies",
      "Archaeology",
      "Christian Religious Studies",
      "Creative Arts",
      "English and International Studies",
      "English Language",
      "Fine and Applied Arts",
      "French",
      "Hausa",
      "History and Diplomatic Studies",
      "History and International Studies",
      "Igbo",
      "Islamic Studies",
      "Linguistics",
      "Literature in English",
      "Music",
      "Performing Arts",
      "Philosophy",
      "Religious Studies",
      "Theatre Arts",
      "Yoruba"
    ]
  },
  {
    name: "Education",
    courses: [
      "Adult Education",
      "Agricultural Science and Education",
      "Business Education",
      "Counselor Education",
      "Early Childhood Education",
      "Education & Arabic",
      "Education & Biology",
      "Education & Chemistry",
      "Education & Christian Religious Studies",
      "Education & Economics",
      "Education & English Language",
      "Education & French",
      "Education & Geography",
      "Education & History",
      "Education & Islamic Studies",
      "Education & Mathematics",
      "Education & Physics",
      "Education & Political Science",
      "Education & Social Studies",
      "Educational Administration",
      "Educational Foundations",
      "Educational Management",
      "Guidance and Counseling",
      "Human Kinetics and Health Education",
      "Library and Information Science",
      "Primary Education Studies",
      "Special Education",
      "Teacher Education Science"
    ]
  },
  {
    name: "Engineering / Environmental / Technology",
    courses: [
      "Agricultural Engineering",
      "Architecture",
      "Building Technology",
      "Chemical Engineering",
      "Civil Engineering",
      "Computer Engineering",
      "Electrical / Electronics Engineering",
      "Environmental Management",
      "Estate Management",
      "Food Engineering",
      "Industrial and Production Engineering",
      "Land Surveying",
      "Marine Engineering",
      "Mechanical Engineering",
      "Mechatronics Engineering",
      "Metallurgical and Materials Engineering",
      "Petroleum Engineering",
      "Quantity Surveying",
      "Structural Engineering",
      "Surveying and Geoinformatics",
      "Urban and Regional Planning",
      "Water Resources and Environmental Engineering"
    ]
  },
  {
    name: "Law",
    courses: [
      "Civil Law",
      "Common Law",
      "Criminology and Security Studies",
      "International Law and Jurisprudence",
      "Islamic / Sharia Law",
      "Law",
      "Private and Islamic Law",
      "Public and International Law"
    ]
  },
  {
    name: "Medical / Pharmaceutical Health Science",
    courses: [
      "Anatomy",
      "Biomedical Technology",
      "Dentistry and Dental Surgery",
      "Human Nutrition and Dietetics",
      "Medical Laboratory Science",
      "Medical Rehabilitation",
      "Medicine and Surgery",
      "Nursing / Nursing Science",
      "Optometry",
      "Pharmacy",
      "Physiology",
      "Physiotherapy",
      "Public Health",
      "Radiography",
      "Veterinary Medicine"
    ]
  },
  {
    name: "Sciences",
    courses: [
      "Applied Geophysics",
      "Biochemistry",
      "Biology",
      "Biotechnology",
      "Botany",
      "Chemistry",
      "Computer Science",
      "Cyber Security",
      "Geology",
      "Industrial Chemistry",
      "Industrial Mathematics",
      "Industrial Physics",
      "Information Technology",
      "Mathematics",
      "Microbiology",
      "Physics",
      "Physics with Electronics",
      "Plant Science and Biotechnology",
      "Software Engineering",
      "Statistics",
      "Telecommunication Science",
      "Zoology"
    ]
  },
  {
    name: "Social Management Science",
    courses: [
      "Accounting",
      "Banking and Finance",
      "Business Management",
      "Criminology",
      "Economics",
      "Entrepreneurship",
      "Geography and Regional Planning",
      "Mass Communication",
      "Peace and Conflict Resolution",
      "Political Science",
      "Psychology",
      "Public Administration",
      "Sociology",
      "Transport Management"
    ]
  }
];

// Raw list of institutions
const RAW_INSTITUTIONS = [
  "A.D Rufa'i College for Legal and Islamic Studies",
  "A.D Rufa'i College for Legal and Islamic Studies (AFFL TO BAYERO UNI. KANO)",
  "A.D Rufa'i College of Education, Legal & General Studies (ND)",
  "Abdu-gusau Polytechnic",
  "Abdullahi Maikano College of Education Wase",
  "Abia State College Of Education",
  "Abia State College of Education (Technical)",
  "Abia State College of Health Sciences and Management Technology",
  "Abia State polytechnic",
  "Abia State University",
  "Abraham Adesanya Polytechnic",
  "Abubakar Ali Polytechnic, Bauchi (NCE Awarding)",
  "Abubakar Garba Zagada-Zagada College of Education",
  "Abubakar Tafawa Balewa University",
  "Abubakar Tatari Ali Polytechnic",
  "Abubakar Tatari Ali Polytechnic- DEG (Affliated to ATBU Bauchi State)",
  "Abuja School of Pension and Requirement Planning",
  "Achievers University",
  "Adamawa State polytechnic",
  "Adamawa State Polytechnic, Yola (Affliated to University Of Maiduguri)",
  "Adamawa State University",
  "Adamu Augie College Of Education",
  "Adamu Garkuwa College of Education",
  "Adamu Tafawa Balewa College of Education, Kangere",
  "Adecom College of Business and Managemet",
  "Adekunle Ajasin University",
  "Adeleke University, Ede",
  "Adeniran Ogunsanya College of Education (Affliate to Ekiti State University)",
  "Adeseun Ogundoyin Polytechnic Formely The Ibarapa Polytechnic, Eruwa",
  "Adeshina College of Education",
  "Adeyemi College of Education",
  "Adeyemi College Of Education, Ondo(Affliated to OAU, Ile-Ife)",
  "Admiralty University of Nigeria",
  "Afe Babalola University",
  "Aflon Digital Institute",
  "African Thinkers Community Of Inquiry College Of Education",
  "Afrihub Ict Institute",
  "Ahmadu Bello University",
  "Ahmadu Bello University Teaching Hospital",
  "Ahman Pategi University, Patigi.",
  "Air Force Institute Of Technology - DEG",
  "Air Force Institute of Technology, Kaduna",
  "Ajayi Crowther University",
  "Ajayi Polytechnic",
  "Akanu Ibiam Federal polytechnic",
  "Akperan Orshi College Of Agriculture",
  "Akperan Orshi Polytechnic, Yandev",
  "Akwa Ibom State College Of Arts And Science",
  "Akwa Ibom State College of Education(Affliated to University of Uyo)",
  "Akwa Ibom State polytechnic",
  "Akwa Ibom State University",
  "Akwa-ibom State College Of Education",
  "Al-Hikma Polytechnic",
  "Al-Hikmah University",
  "Al-Ibadan College of Education",
  "Al-Qalam University, Katsina",
  "Alhikma College Of Education",
  "Allover central polytechnic",
  "Alvan Ikoku Federal College Of Education (Affliated to University of Nigeria Nsukka)",
  "Alvan Ikoku University Of Education",
  "Ambassador College Of Management And Technology",
  "Ambassador College Of Technology And Paralegal Studies",
  "Ambrose Alli University",
  "Ameenuddeen College of Education, Kano",
  "Ameer Shehu Idris College of Advance Studies",
  "American University of Nigeria",
  "Aminu Dabo College of Health Sciences and Technology",
  "Aminu Kano College of Islamic and Legal Studies",
  "Aminu Kano Teaching Hospital",
  "Anambra State College of Agriculture",
  "Anambra State College of Health Technology, Obosi",
  "Anambra state polytechnic",
  "Anchor University",
  "Angel Crown College Of Education",
  "Annur Institute for Islamic Education",
  "Ansar-ud-deen College Of Education",
  "Apa College Of Education",
  "Arabic And Islamic College Of Education",
  "Archbishop Vining College of Theology (Affiliated to University of Ibadan)",
  "Archbishop Vining College of Theology",
  "Arewa Paralegal Innovation Enterprise",
  "Arthur Jarvis University",
  "Ashi Polytechnic, Anyiin",
  "Assanusiyah College Of Education",
  "Atiba University, Oyo",
  "Atiku Abubakar College of Legal and Islamic Studies",
  "Auchi polytechnic",
  "Auchi Polytechnic, Edo State (Affiliated to Nnamdi Azikiwe University, Awka)",
  "Audu Bako College Of Agriculture Danbatta",
  "Augustine University",
  "Ave Maria University",
  "Awori District College Of Education",
  "Baba Mayaki College of Education",
  "Babcock University",
  "Bamidele Olumilua University Of Education, Science and Technology.",
  "Baptist College of Theology, Benin (Affiliated to Ambrose Alli University)",
  "Baptist College of Theology, Obinze, Owerri (Affiliated to University of Por-Harcourt)",
  "Bartholomew College of Health Technology",
  "Bauchi College of Agriculture",
  "Bauchi institute for Arabic & islamic studies",
  "Bauchi State College Of Agriculture",
  "Bauchi State Institute of Education, Kangere",
  "Bauchi State University",
  "Bayelsa Medical University",
  "Bayelsa State College of Arts and Science",
  "Bayelsa State College Of Education",
  "Bayelsa State College of Health Technology",
  "Bayelsa State Polytechnic, Aleibiri",
  "Bayero University Kano",
  "Bayotijani College Of Education",
  "Baze University",
  "Bellarks Polytechnic Kwale",
  "Bells University of Technology",
  "Benson Idahosa University",
  "Benue State Poly",
  "Benue State University",
  "Best Legacy College Of Education",
  "Best solution polytechnic",
  "Bethel College of Education,",
  "Biga College of Education",
  "Bigard Memorial Seminary, Enugu (Affiliated to University of Ibadan)",
  "Bilyaminu Othman College of Education",
  "Bingham University",
  "Binyaminu Usman College of Agriculture",
  "Bolmor Polytechnic",
  "Borno State University",
  "Bowen University",
  "Buckingham Academy Of Management And Technology",
  "Bukar Abba Ibrahim University",
  "Business Education Examination Council",
  "Caleb University",
  "Calvary College of Theology, Port Harcourt (Affiliated to University of Calaba",
  "calvary polytechnic",
  "Calvin Foundation College Of Education",
  "Capital City University, Warawa, Kano",
  "Caritas University",
  "Catholic Institute of West Africa, Port Harcourt (Affiliated to University of Calabar)",
  "Catholic University of Nigeria",
  "Centre For Creative Arts Education",
  "Cetep University",
  "Charkin Maritime Academy, Port Harcourt",
  "Chrisland University",
  "Christopher University",
  "Chukwuemeka Odumegwu Ojukwu University (former ANSU)",
  "Cifman Institute Of Techn. & Management",
  "Citi Polytechnic, Abuja",
  "City College Of Education",
  "City Gate Institute Of Innovation And Technology",
  "Claretian University Nekede, Imo State (Formerly Claretain Institute of Philosophy)",
  "Clifford University",
  "Coal City University",
  "Coastal Polytechnic",
  "College Of Administrative And Business Studies",
  "College Of Agriculture And Animal Science",
  "College of Agriculture and Animal Science, Bakura",
  "College of Agriculture Kabba",
  "College Of Agriculture, Hadijia",
  "College Of Agriculture, Jalingo",
  "College Of Agriculture, Kabba",
  "College Of Agriculture, Lafia",
  "College Of Agriculture, Zuru",
  "College of Arabic and Islamic Legal Studies, Ilorin (Affiliated to Bayero University)",
  "College of Business and Management Studies, Konduga",
  "College of Education Darazo",
  "College Of Education, Agbor",
  "College of Education, Agbor (Affiliated to Delta State University, Abraka)",
  "College of Education, Akamkpa",
  "College Of Education, Akwanga",
  "College Of Education, Akwanga (Affiliated to Ahmadu Bello University Zaria)",
  "College Of Education, Ankpa",
  "College Of Education, Ankpa (Affiliated to ATBU, Bauchi)",
  "College Of Education, Azare",
  "College Of Education, Azare (Affiliated to University of Maiduguri)",
  "College of Education, Billiri",
  "College Of Education, Ekiadolor",
  "College of Education, Ero-Akure",
  "College Of Education, Foreign Links Campus Moro",
  "College Of Education, Gidan-waya, Kafanchan",
  "College Of Education, Gidan-waya, Kafanchan (Affiliated to ABU)",
  "College Of Education, Gindiri",
  "College Of Education, Hong",
  "College Of Education, Hong  (Affiliated to Ahmadu Bello University)",
  "College Of Education, Igueben",
  "College Of Education, Ikere",
  "College Of Education, Ikere  (Affiliated to University of Nigeria, Nsukka)",
  "College Of Education, Ilemona",
  "College Of Education, Ilesa",
  "College Of Education, Ilesa (Affiliated to University of Ibadan)",
  "College Of Education, Ilorin",
  "College Of Education, Jalingo",
  "College Of Education, Katsina-ala",
  "College Of Education, Katsina-ala (Affiliated to University of Calabar)",
  "College of Education, Kura",
  "College Of Education, Maru",
  "College Of Education, Moro-ife",
  "College of Education, Mosogar (Affiliated to Delta State University, Abraka)",
  "College Of Education, Oju",
  "College Of Education, Oju - (Affiliated to Benue State University)",
  "College Of Education, Oro",
  "College Of Education, Oro (Affiliated to Ekiti State University)",
  "College Of Education, Port Harcourt",
  "College Of Education, Waka-biu",
  "College Of Education, Waka-biu (Affiliated to University of Maiduguri)",
  "College Of Education, Warri",
  "College Of Education, Warri (Affiliated to Delta State University, Abraka)",
  "College Of Education, Warri (Affiliated to University Benin)",
  "College of Education, Zing",
  "College of Education, Zing (Affiliated to Ahmadu Bello University)",
  "College of Health and Technology, Ile-Ife",
  "College Of Health Sciences And Technology",
  "College Of Health Technology Ningi",
  "College of Health Technology, Calabar",
  "College of Health Technology, Zawan",
  "College of Seminary and Theology, Irri",
  "College of Seminary and Theology, Irri (Affiliated to Niger Delta University, Wilberforce Island)",
  "College of Technology, Iresi",
  "Confluence University Of Science and Technology",
  "Cornerstone College Of Education, Lagos",
  "Corona College of Education, Lekki",
  "Covenant College Of Education",
  "Covenant Polytechnic, Aba",
  "Covenant University",
  "Crawford University",
  "Crescent University",
  "Crestfield  College of Education, Erin Osun",
  "Cross River State College Of Education",
  "Cross River State College Of Education (Affiliated to University of Calabar)",
  "Cross River State Institute of Tech. and Management, Ugep",
  "Crown Polytechnic",
  "Crown-Hill University",
  "D.S Adegbenro ICT Polytechnic",
  "Dalewares Institute Of Technology",
  "David Nweze Umahi University of Medical Sciences",
  "Delar College Of Education",
  "Delta State College Of Agriculture",
  "Delta State College Of Health Technology Ofuoma Ughelli",
  "Delta State College Of Physical Education (Affiliated to University of Benin)",
  "Delta State College Of Physical Education, Mosogar",
  "Delta State Polytechnic, Ogwashi-Uku",
  "Delta State Polytechnic, Otefe-Oghara",
  "Delta State School of Marine Technology, Burutu",
  "Delta State University Of Science And Technology",
  "Delta State University, Abraka",
  "Dennis Osadebay University, Anwai (formely Delta State University Anwai campus)",
  "Diabo Paralegal Training Institute",
  "Diamond College of Education",
  "Distance Learning Centre, Ahmadu Bello University",
  "Dominican University, Ibadan",
  "Dominion University",
  "Dorben polytechnic",
  "Dreamville Ltd (ladela School Abuja)",
  "E-LEARNING NOUN",
  "E-LEARNING UDUSOK",
  "E-LEARNING UNILAG",
  "E-Learning UNIMAID",
  "E-LEARNING UNIUYO",
  "Eastern Palm University",
  "Eastern Polytechnic",
  "Ebenezer College Of Education",
  "Ebonyi State College Of Education, Ikwo",
  "Ebonyi State College of Education, Ikwo (Affiliated to EBSU)",
  "Ebonyi State University",
  "ECWA College of Education, Igbaja",
  "ECWA College of Education, Jos",
  "ECWA Theological Seminary, Igbaja (Affiliated to University of Ibadan)",
  "Ed-John School Of Management, Ikorodu",
  "Edo State College Of Agriculture",
  "Edo State College of Education",
  "Edo State Institute Of Technology And Management",
  "Edo State Poly Usen",
  "Edo State University Uzairue (Formerly Edo University Iyamho)",
  "Edwin Clark University",
  "Ekiti State College Of Agriculture And Technology, Isan-Ekiti",
  "Ekiti State University",
  "Eko University of Medicine and Health Sciences",
  "Elder Oyama Memorial College Of Education",
  "Elechi Amadi Polytechnic",
  "Elizabeth Memorial College of Education",
  "Elizade University",
  "Emirates College Of Health Science And Technology",
  "Emirates College Of Health Science And Technology  (Affiliated to KWASU)",
  "Emmanuel Alayande College Of Education",
  "Emmanuel Ebije Ikwue College of Education",
  "Enugu State College of Agriculture",
  "Enugu State College Of Education, Technical (Affiliated to Nnamdi Azikiwe University)",
  "Enugu State College Of Education, Technical",
  "Enugu state polytechnic",
  "Enugu State University Of Science And Technology",
  "Enville Institute of Management and Technology Polytechnic",
  "Essien Ukpabia Presbyterian Theological College, Itu, Akwa Ibom State",
  "Evangel University",
  "Farmark Institute Of Employment And Creativity Kaduna",
  "FCT College Of Education, Zuba",
  "FCT College Of Education, Zuba (Affiliated to Ahmadu Bello University)",
  "Federal College of Agricultural Produce Technology",
  "Federal College of Agriculture, Ado-Ekiti/Owo",
  "Federal College Of Agriculture, Akure",
  "Federal College Of Agriculture, Ishiagu",
  "Federal College Of Agriculture, Moor Plantation",
  "Federal College Of Animal Health & Production Tech, Ibadan",
  "Federal College Of Animal Health & Production Tech, Vom",
  "Federal College Of Animal Health & Production Tech, Vom (Affiliated to Abubakar Tafawa Balewa Uni)",
  "Federal College of Dental Technology and Therapy (Affiliated to FUTO)",
  "Federal College Of Education (Special), Oyo",
  "Federal College Of Education (Special), Oyo-  DEG",
  "Federal College Of Education (Techinical) Bichi",
  "Federal College Of Education (Technical) Akoka",
  "Federal College Of Education (Technical) Akoka- (Affiliated to UNIBEN)",
  "Federal College Of Education (Technical) Gusau",
  "Federal College Of Education (Technical) Gusau (Affiliated to Ahmadu Bello University)",
  "Federal College Of Education (Technical) Gusau (Affiliated to FUTMINNA)",
  "Federal College Of Education (Technical) Omoku",
  "Federal College Of Education (Technical) Omoku (Affiliated to University of Uyo)",
  "Federal College of Education (Technical) Potiskum (Affiliated to Abubakar Tafawa Balewa University)",
  "Federal College Of Education (Technical) Umunze - DEG",
  "Federal College Of Education (Technical) Umunze",
  "Federal College of Education (Technical), Asaba",
  "Federal College of Education (Technical), Asaba (Affiliated to UNIBEN)",
  "Federal College Of Education (Technical), Gombe (Affiliated to Abubakar Tafawa Balewa University)",
  "Federal College Of Education (Technical), Gombe",
  "Federal College Of Education Abeokuta (Affiliated to University of Ibadan)",
  "Federal College Of Education Abeokuta",
  "Federal College Of Education Asaba",
  "Federal College of Education Gidan Madi",
  "Federal College of Education Gusua, Zaria",
  "Federal College Of Education Katsina",
  "Federal College Of Education Katsina (Affiliated to Bayero University)",
  "Federal college of Education Kontagora (Affiliated to Amadu Bello university)",
  "Federal college of Education Kontagora",
  "Federal College Of Education Obudu",
  "Federal College Of Education Obudu (Affiliated to University of Calabar)",
  "Federal College Of Education Okene",
  "Federal College Of Education Okene (Affiliated to University of Ibadan)",
  "Federal College Of Education Potiskum",
  "Federal College Of Education Yola (Affiliated to UNIMAID)",
  "Federal College Of Education Yola",
  "Federal College Of Education Zaria",
  "Federal College Of Education Zaria (Affiliated to Ahmadu Bello University)",
  "Federal College Of Education, Eha-amufu",
  "Federal College Of Education, Eha-amufu (Affiliated to University of Nigeria, Nsukka)",
  "Federal College of Education, Ekiadolor",
  "Federal College of Education, Iwo",
  "Federal College of Education, Jama'are",
  "Federal College Of Education, Kano",
  "Federal College Of Education, Kano (Affiliated to Ahmadu Bello University)",
  "Federal College of Education, Odugbo",
  "Federal College of Education, Pankshin",
  "Federal College of Education, Pankshin (Affiliated to University of Jos)",
  "Federal College Of Fisheries And Marine Technology",
  "Federal College Of Forestry Technology, Ibadan",
  "Federal College Of Forestry, Jos",
  "Federal College Of Forestry, Mechanisation, Afaka",
  "Federal College Of Freshwater Fisheries Tech, Baga",
  "Federal College Of Freshwater Fisheries Tech, New Bussa",
  "Federal College Of Horticulture, Dadin Kowa",
  "Federal College Of Land Resources Technology, Kuru",
  "Federal College Of Land Resources Technology, Owerri",
  "Federal College Of Orthopedic Technology, Igbobi",
  "Federal College Of Wildlife Management, New Bussa",
  "Federal Cooperative College, Ibadan",
  "Federal Cooperative College, Kaduna",
  "Federal Cooperative College, Oji River",
  "Federal Polytechnic Ado-Ekiti (Affiliated to FUTMINNA)",
  "Federal Polytechnic Ado-Ekiti",
  "federal polytechnic bal",
  "Federal Polytechnic Bauchi (Affiliated to Abubakar Tafawa Balewa University)",
  "Federal Polytechnic Daura",
  "Federal Polytechnic of Oil and Gas, Bonny",
  "Federal Polytechnic, Bali",
  "Federal polytechnic, Bauchi",
  "Federal polytechnic, Bida",
  "Federal Polytechnic, Bida (Affiliated to FUTMINNA)",
  "Federal polytechnic, Birnin-Kebbi",
  "Federal polytechnic, Damaturu",
  "Federal polytechnic, Ede",
  "Federal Polytechnic, Ekowe",
  "Federal polytechnic, Idah",
  "Federal polytechnic, Ilaro",
  "Federal Polytechnic, Ile-Oluji",
  "Federal Polytechnic, Kaura Namoda",
  "Federal polytechnic, Mubi",
  "Federal polytechnic, Nasarawa",
  "Federal polytechnic, Nekede",
  "Federal Polytechnic, Offa",
  "Federal Polytechnic, Offa, Kwara (Affiliated to FUTMINNA)",
  "Federal polytechnic, Oko",
  "Federal Polytechnic, Ukana",
  "Federal School Of Dental Technology And Therapy, Enugu",
  "Federal School Of Social Works",
  "Federal School of Statistics, Ibadan",
  "Federal School of Statistics, Manchok",
  "Federal School Of Surveying, Oyo",
  "Federal Training Centre Kaduna",
  "Federal Training Centre Lagos",
  "Federal University Gashua",
  "Federal University Gusau",
  "Federal University of Agriculture, Abeokuta",
  "Federal University Of Agriculture, Makurdi",
  "Federal University Of Agriculture, Zuru, Kebbi",
  "Federal University of Petroleum Resource",
  "Federal University of Technology Akure",
  "Federal University of Technology Minna",
  "Federal University of Technology, Owerri",
  "Federal University, Birnin Kebbi",
  "Federal University, Dutse",
  "Federal University, Dutsin-ma",
  "Federal University, Kashere",
  "Federal University, Lafia",
  "Federal University, Lokoja",
  "Federal University, Ndufu-alike",
  "Federal University, Otuoke",
  "Federal University, Oye-ekiti",
  "Federal University, Wukari",
  "Festmed College of Education",
  "Fidei Polytechnic, Gboko",
  "First Technical University, Ibadan",
  "Flyingdove Institute Of Information Technology, Abuja",
  "Fountain University",
  "Gateway polytechnic Saapade",
  "Gboko College of Education",
  "Gboko Polytechnic",
  "Global College of Education",
  "Godfrey Okoye University",
  "GOMBE STATE COLLEGE OF EDUCATION AND LEGAL STUDIES",
  "Gombe State College Of Health Sciences And Technology, Kaltungo",
  "Gombe State College Of Nursing And Midwifery",
  "Gombe State Polytechnic",
  "Gombe State university",
  "Gombe State University of Science and Technology",
  "Good Shepherd College of Education",
  "Grace College of Education, Osogbo, Osun State",
  "Grace Polytechnic, Lagos",
  "GraceLand Polytechnic",
  "Greenfield University, Kaduna",
  "Gregory University, Uturu",
  "Grundtvig Polytechnic",
  "Hallmark University",
  "Hamzainab College Of Education, Osogbo",
  "Harry Pass Polytechnic, Tse Usen Mkar",
  "HARVARDE COLLEGE OF MANAGEMENT AND BUSINESS STUDIES, ABEOKUTA,",
  "Hassan Usman Katsina Poly",
  "Hassan Usman Katsina Polytechnic (Affiliated to FUTMINNA)",
  "Havard Wilson College Of Education, Aba",
  "Havilla University, Nde-Ikom, Cross River",
  "Heritage Polytechnic",
  "Hezekiah University",
  "Highland College Of Tech. & Further Education",
  "Hill College Of Education",
  "Hope and Anchor College of Education",
  "Hussaini Adamu Federal polytechnic",
  "I-Con Universal Polytechnic",
  "Ibadan City Polytechnic",
  "IBOM METROPOLITAN POLYTECHNIC, ATAN OFFOT",
  "Ibrahim Badamasi Babangida University",
  "Ifo College Of Management And Technology",
  "Igbajo Polytechnic",
  "Igbinedion University",
  "Ignatius Ajuru University",
  "Ihechukwu Madubuike Institute of Technology",
  "Ilori College of Education",
  "Imam Hamzat College of Education",
  "Imam Saidu College of Education",
  "Imfi, Ict Academy, Uyo",
  "Immanuel College of Technology and Christian Education , Samonda, Ibadan",
  "Immanuel College of Technology and Christian Education , Samonda, Ibadan (Affiliated to University o",
  "Imo State College of Education",
  "Imo State College Of Nursing And Health Sciences",
  "Imo State Polytechnic",
  "Imo State University",
  "Innovation Institute Of Technology, Kaduna",
  "Institute of Administration Kongo",
  "Institute of Ecumenical Education, Thinker Corner, Enugu",
  "Institute of Health Technology UBTH",
  "Institute of Management and Technology Enugu (Affiliated to University of Nigeria)",
  "Institute of Management Technology, Enugu",
  "Institute Of Public Health (OAU), Ile-ife",
  "Institute of Technology and Management",
  "Interlink Polytechnic",
  "International Institute Of Tourism And Hospitality, Yenagoa",
  "Ipere College of Education",
  "Isa Kaita College Of Education",
  "Isa Kaita College of Education, Dutsinma (Affiliate to Ahmadu Bello University)",
  "Isa Mustapha Agwai I Polytechnic",
  "Isaac Jasper Boro College of Education",
  "Isaac Jasper Boro College of Education (Affiliated to Niger Delta University)",
  "Iwo City Polytechnic",
  "Jama'atu Nasir Islam College Of Education, Kaduna",
  "Jibwis College Of Arabic And Islamic Education, Gombe",
  "Jibwis College of Education Bauchi",
  "Jibwis College of Education Potiskum",
  "Jibwis College of Education, Keffi",
  "Jigawa State College of Education and Legal Studies",
  "Jigawa State College Of Education, Gumel",
  "Jigawa State College Of Education, Gumel (Affiliated to Bayero University)",
  "Jigawa State College of Islamic and Legal Studies",
  "Jigawa State Institute Of Information Technology",
  "Jigawa State Polytechnic",
  "Joseph Ayo Babalola University",
  "Kaduna Business School",
  "Kaduna Polytechnic",
  "Kaduna Polytechnic, Kaduna (Affiliated to FUTMINNA)",
  "Kaduna Polytechnic, Tunda (Affiliated to Ahmadu Bello University)",
  "Kaduna State university",
  "Kalac Christal Polytechnic",
  "Kano State College of Education & Preliminary Studies",
  "Kano State College of Health Science and Technology",
  "Kano State polytechnic",
  "Kano State Polytechnic, (NCE)",
  "Kano University Of Science And Technology",
  "Karl Kumm University, Vom, Plateau State",
  "Karrox-ugrl Computer Education & Training Centre",
  "Kashim-ibrahim College Of Education, Maiduguri",
  "Kashim-ibrahim College Of Education, Maiduguri (Affiliated to UNIMAID)",
  "Katsina State College Of Health Sciences Technology",
  "Katsina State College Of Nursing And Midwifery",
  "Katsina University",
  "Kazaure College of Education",
  "Kebbi State College Of Education, Argungu",
  "Kebbi State University Of Science And Technology",
  "Ken Saro-Wiwa Polytechnic",
  "Khadija University, Majia, Jigawa State",
  "Kings Polytechnic",
  "Kings University",
  "Kinsey College Of Education, Ilorin",
  "Kogi State College of Education (Technical)",
  "Kogi State College of Health Sciences & Technology Idah",
  "Kogi State Polytechnic",
  "kogi State University",
  "KolaDaisi University",
  "Kwara State College of Arabic and Islamic Legal Studies, Ilorin",
  "Kwara State College Of Education (Technical), Lafiagi",
  "Kwara State College Of Education (Technical), Lafiagi (Affiliated to Ahmadu Bello University)",
  "Kwara State College of Education, Ilorin",
  "Kwara State College of Education, Ilorin, Kwara State",
  "Kwara State College of Education, Oro",
  "Kwara State College of Health Technology",
  "Kwara State polytechnic",
  "Kwara State University",
  "Kwararafa College Of Education, Otukpo",
  "Kwararafa University",
  "Ladoke Akintola University of Technology",
  "Lagos City Computer College, Lagos",
  "Lagos City polytechnic",
  "Lagos State College of Health Technology.",
  "Lagos State College Of Nursing And Midwifery Igando",
  "Lagos State polytechnic",
  "Lagos State University",
  "Lagos State University of Education (Formerly, Adeniran Ogunsanya College of Education)",
  "Lagos State University of Education (Formerly, Michael Otedola College Of Primary Education)",
  "Lagos State University of Science and Technology (Formerly, Lagos State Polytechnic)",
  "Lagos University Teaching Hospital",
  "Land Mark Polytechnic",
  "Landmark University",
  "Lani Stephens Music Institute",
  "Lapo Institute For Microfinance And Enterprise Development, Benin",
  "Laser Petroleum Geo-sciences Centre",
  "Lead City University",
  "Legacy University",
  "Lens Polytechnic Offa",
  "Lessel College of Education",
  "Life Theological Seminary",
  "LifeGate College Of Education",
  "Light House Polytechnic",
  "Linet Paul Innovative Institute",
  "Literacy College Of Management And Technology",
  "Lufodo Academy Of Performing Arts",
  "Madonna University",
  "Mai Idris Alooma Polytechnic",
  "Mainland College of Technology",
  "Malikiya College of Health and Social Sciences",
  "Mallam Yahaya Hamza Institute Of Advance Studies,",
  "Maranatha University",
  "Marist Polytechnic",
  "Maritime Academy of Nigeria",
  "Maryam Abacha, American University of Nigeria",
  "Mater Dei Polytechnic",
  "McPherson University",
  "Meadow Hall College of Education",
  "Metallurgical Training Institute, Onitsha",
  "Meteorological Institute of Science and Technology",
  "Methodist Theological Institute, Umuahia",
  "Metro College of Education Adogi-Lafia",
  "Metropolitan Institute Of Technology",
  "Mewar University Nigeria",
  "Michael & Cecilia Foundation College of Education",
  "Michael Imodu National Institute for Labour Studies",
  "Michael Imodu National Institute for Labour Studies (Affiliated to University of Ilorin",
  "Michael Okpara University of Agriculture, Umudike",
  "Michael Otedola College Of Primary Education, Moforiji (Affiliated to University of Ibadan)",
  "Micheal and Cecilia Ibru University",
  "Millennium College of Health Technology",
  "Modibbo Adama University of Technology",
  "Mohammed Goni College Of Legal And Islamic Studies",
  "Mohammed Lawan College Of Agriculture, Maiduguri",
  "Moje College of Education",
  "Moshood Abiola polytechnic",
  "Mountain Top University",
  "Mudiame University",
  "Muftau' Lanihun College Of Education",
  "Muhyideen College Of Education, Ilorin",
  "Muritadha College Of Education (Institute Of Arabic And Islamic Studies, Olodo)",
  "Murtadha Col. Of Edu. Inst. Of Arabic & Islamic Legal Studies",
  "Nacabs Polytechnic",
  "Nana Aishat Memorial College Of Education",
  "Nasarawa State College of Health Science and Technology, Keffi",
  "Nasarawa State Polytechnic",
  "Nasarawa State University",
  "National Film Institute",
  "National Film Institute (Affiliated to University of Jos)",
  "National Institute for Construction Technology, Uromi",
  "National Institute for Nigeria Languages",
  "National Library of Nigeria",
  "National Missionary Seminary of St-Paul, Gwagwalada",
  "National Open University of  Nigeria",
  "National Teachers Institute, Kaduna",
  "National Water Resources Institute",
  "Nazareth Institute of Health Science and Technology",
  "New Gate College of Health Technology",
  "Niger Delta University",
  "Niger State College Of Agriculture, Mokwa",
  "Niger State College of Education,  Minna, Niger State",
  "Niger State College of Education, Minna (Affiliated to Ahmadu Bello University)",
  "Niger State College of Education, Minna (Affiliated to Usman Danfodiyo University)",
  "Niger State polytechnic",
  "Nigeria Army College of medical Sciences",
  "Nigeria Army Institute of Technology and Environmental Studies",
  "Nigeria Army School Of Military Engineering, Makurdi",
  "Nigeria Baptist Theological Seminary, Ogbomosho",
  "Nigeria Institute of Mining and Geoscience",
  "Nigeria Police Academy",
  "Nigerian Air Force College of Nursing",
  "Nigerian Army College of Environmental Science and Technology",
  "Nigerian Army College of Nursing and Midwifery",
  "Nigerian Army School of Education",
  "Nigerian Army School of Education (Affiliated to Tai Solarin University of Education)",
  "Nigerian Army School Of Finance And Administration",
  "Nigerian Army University, Borno",
  "Nigerian Christian Bible College, Ukpom",
  "Nigerian College of Aviation Technology",
  "Nigerian Defence Academy",
  "Nigerian Institute Of Journalism, Ikeja",
  "Nigerian Institution of Leather Technology and Science Technology",
  "Nigerian Maritime University",
  "Nigerian Navy of Finance And Logistics College",
  "Nigerian Navy School of Health Science, Offa",
  "Nigerian Police Academy, Wudil, Kano State",
  "Nigerian Television Authority Television College",
  "NIIT",
  "Nile University of Nigeria",
  "NKST College of Health Technology",
  "Nnamdi Azikiwe University",
  "Nnamdi Azikiwe University Teaching Hospital",
  "Nogak Polytechnic",
  "Nok University, Kachia, Kaduna State",
  "Northwest University, Kano (Now Yusuf Maitama Sule University)",
  "Nosakhare College of Education",
  "Novelty Polytechnic",
  "Novena University",
  "Nuhu Bamalli polytechnic",
  "Nuhu Bamalli Polytechnic, Zaria, Kaduna (NCE Awarding)",
  "Nwafor Orizu College Of Education, Nsugbe",
  "Nwafor Orizu College Of Education, Nsugbe ( University of Nigeria Nsukka)",
  "OAK Business School, River View Estate",
  "Obafemi Awolowo University",
  "Obafemi Awolowo University Teaching Hospital Complex",
  "Obong University",
  "Oduduwa University",
  "Ogun State College of Health Technology",
  "Ogun State Institute of Technology",
  "Olabisi Onabanjo University",
  "Olusegun Agagu University of Science and Technology (Formerly Ondo State University of Science and T",
  "Ondo State School of Health Technology",
  "Onit College Of Education Abagana",
  "Osun State College Of Education, Ila-orangun",
  "Osun State College Of Education, Ila-orangun (Affiliated to Ekiti State University)",
  "Osun State College of Technology",
  "Osun State polytechnic",
  "Osun State Polytechnic, Iree, Osun State (NCE Awarding)",
  "Osun State School Of Health Technology",
  "Osun State University",
  "Oswald Waller College of Education",
  "Our Saviour Institute of Science, Agric. & Tech.",
  "Oyo State College Of Agriculture",
  "Oyo State College Of Education",
  "Oyo State College Of Health Sciences And Technology, Eleyele Ibadan",
  "Pamo University of Medical Sciences",
  "Pan African College of Education",
  "Pan-African Institute of Paralegal Studies",
  "Pan-Atlantic University",
  "Paul University",
  "Peace College of Education, Enokpoli",
  "Peace land College of Education",
  "Peacock College of Education, Jalingo",
  "Peter Achimugu College of  Theology, Ankpa.",
  "Petroleum Training Institute",
  "Philomath University, Kuje",
  "Piaget College of Education",
  "Plateau State College Of Agriculture, Garkawa",
  "Plateau State Polytechnic",
  "Plateau State University",
  "POGIL College of Health Technology",
  "Polytechnic Of Sokoto",
  "Pope John Major Seminary, Okpun, Awka",
  "Port Harcourt Polytechnic, Rumuola",
  "Precious Cornerstone University",
  "Prime Polytechnic",
  "Ramat polytechnic",
  "Redeemed Christian Bible College",
  "Redeemer's University",
  "Redeemer’s College of Technology and Management",
  "Renaissance University",
  "Rhema University",
  "Ritman University",
  "Rivers State College Of Arts And Science",
  "Rivers State College Of Health Science And Technology",
  "Rivers State polytechnic",
  "Rivers State University",
  "Ronik Polytechnic",
  "Royal City College Of Education",
  "Rufus Giwa polytechnic",
  "Saadatu Rimi College of Education, Kumbotso",
  "Saadatu Rimi College of Education, Kumbotso (Affiliated to Ahmadu Bello University)",
  "Saadatu Rimi College of Education, Kumbotso (Affiliated to Bayero University)",
  "SAF Polytechnic Iseyin",
  "Salem University",
  "Samaru College Of Agriculture",
  "Samuel Adegboyega University",
  "sarkin yamma community college of education",
  "Savannah Institute Of Technology (Affiliated to Federal University, Wukari)",
  "School  of Health Information Management, University of Uyo Teaching Hospital",
  "School Of Agriculture, Bauchi",
  "School Of Agriculture, Ikorodu",
  "School Of Biomedical Engineering, University of Benin Teaching Hospital",
  "School of Biomedical Engineering, University of Lagos Teaching Hospital, Lagos",
  "School of Biomedical Engineering, University of Maiduguri Teaching Hospital",
  "School of Health Information Management (UCH-Ibadan)",
  "School of Health Information Management, Lagos University Teaching Hospital",
  "School of Health Information Management, UBTH",
  "School Of Nursing, Wesley Guilds Hospital, Oauthc, Ilesa, Osun State",
  "School Of Orthopedic Cast Technology Hospital Enugu",
  "School Of Orthopedic Cast Technology Teaching Hospital Ilorin",
  "School of Orthopedic Hospital",
  "Seat of Wisdom Seminary, Owerri (Affiliated to IMSU)",
  "Seminary of All Saints, Uhiele, Ekpoma (Affiliated to UNIBEN)",
  "Shaka Momodu Polytechnic",
  "Shehu Idris College Of Health Sci & Tech, Makarfi",
  "Shehu Shagari College of Education (Affl to Ahmadu Bello University, Zaria)",
  "Shehu Shagari College of Education (Affl to Usman Dan-Fodio University, Sokoto)",
  "Shehu Shagari College Of Education, Sokoto",
  "Shehu Sule College Of Nursing And Midwifery Damaturu Yobe State",
  "Sheik Ibrahim El-Tayeb Institute, Kano (Affiliated to Bayero University)",
  "Sinai College Of Education",
  "Skyline University, Kano",
  "Sokoto State University",
  "South Eastern College of Computer Engineering and Info. Tech.",
  "Southern Atlantic Polytechnic",
  "Southern-nigeria Institute Of Innovative Technology",
  "SouthWestern University",
  "Speedway Polytechnic",
  "Spiritan International School of Theology, Attakwu (Affiliated to University of Nigeria Nsukka)",
  "Spiritan School of Philosophy, Issienu Nsukka (Affiliated to University of Nigeria Nsukka)",
  "Spiritan University",
  "St-Joseph Major Seminary, Ikot-Ekpene (Affiliated to University of Calabar)",
  "St. Albert Institute, Kafanchan (Affiliated to University of Jos)",
  "ST. Albert the Great Major Seminary, Abeokuta (Affiliated to University of Benin)",
  "St. Augustine College Of Education",
  "St. Augustine College Of Education, Yaba (Affiliated to University of Ibadan)",
  "St. Mary Polytechnic",
  "St. Peter and Paul Seminary Bodija, Ibadan",
  "Stars Polytechnic, Agbedi-Atan",
  "Steady Flow College of Education",
  "Sule Lamido University (Former Jigawa State University)",
  "Summit University Offa",
  "Sunnah College of Education, Kofar Bauchi",
  "Sure Foundation Polytechnic",
  "Tai Solarin College of Education, Ijebu-Ode",
  "Tai Solarin College of Education, Ijebu-Ode (Affiliated to Olabisi Onabanjo University)",
  "Tai Solarin University of Education",
  "Tansian University",
  "Taraba State Polytechnic",
  "Taraba State University",
  "Temple-gate Polytechnic",
  "The African Church College Of Education",
  "The Apostolic Church Theological Seminary, Amumara",
  "The College of Education, Lanlate",
  "The College Of Education, Nsukka",
  "The Federal University of Health Sciences , Otukpo",
  "The Global Polytechnic",
  "The Mbanza Kongo Polytechnic",
  "The Oke-Ogun Polytechnic, Saki",
  "The Polytechnic Adoka",
  "The Polytechnic Igbo-Owu",
  "The polytechnic, Ibadan",
  "The Polytechnic, Ile-Ife",
  "The Polytechnic, Imesi-Ile",
  "The Samuel Bill Theological College, Abak",
  "The School Of Information And Media Technology",
  "The University of Africa, Toru-Orua",
  "The University of Agriculture and Environmental Sciences, Umuagwo",
  "The University Of Education, Ikere-Ekiti",
  "Thomas Adewumi University, Oko-Irese,",
  "TimeOn Kairos Polytechnic",
  "Topfaith University, Mkpatak,",
  "Topmost College Of Education",
  "Tower Polytechnic, Ibadan",
  "Trinity Polytechnic",
  "Trinity Theological College,  Umuahia",
  "Trinity University",
  "Tropical College Of Health Sciences & Technology",
  "Turath College of Islamic College",
  "Uli College of Education",
  "UMA UKPAI POLYTECHNIC, ASAGA",
  "Uma Ukpai School of Theology, Uyo (Affiliated to University of Uyo)",
  "Umar Ali Shinkafi Polytechnic",
  "Umar Bun Khattab College of Education",
  "Umar Ibn Ibrahim El-Kanemi College Of Education, Science and Technology, Bama",
  "Umar Ibn Ibrahim El-Kanemi College Of Education, Science and Technology, Bama (Affl to UNIMAID)",
  "Umar Suleiman College Of Education, Gashua",
  "Umar Suleiman College Of Education, Gashua (Affiliated to UNIMAID)",
  "Umar-Ibn Ei-Kanemi College of Education",
  "Umaru Musa Yar'adua University",
  "UMCA Theological College, Ilorin",
  "Unity College Of Education, Aukpa-adoka",
  "University College Hospital, Ibadan",
  "University of Abuja",
  "UNIVERSITY OF AFRICA,",
  "University of Benin",
  "University of Calabar",
  "University Of Calabar Teaching Hospital",
  "University of Cross River State (Formerly CRUTECH)",
  "University of Delta State Agbor",
  "University of Ibadan",
  "University of Ilorin",
  "University of Ilorin Teaching Hospital",
  "University of Jos",
  "University of Lagos",
  "University of Maiduguri",
  "University of Maiduguri Sandwich",
  "University of Maiduguri Teaching Hospital",
  "University of Medical Sciences, Ondo State",
  "University Of Mkar",
  "University Of Nigeria Nsukka",
  "University Of Offa",
  "University of Port Harcourt Teaching Hospital,",
  "University of Port-Harcourt",
  "University Of Science And Technology, Ifaki-ekiti",
  "University of Uyo",
  "Upland College Of Education",
  "Usman Dan Fodio University",
  "Usmanu Danfodiyo University Teaching Hospital",
  "Uyo City Polytechnic",
  "Valley View Polytechnic",
  "Veritas University, Abuja",
  "Wavecrest College of Hospitality",
  "Waziri Umaru Fed. Polytechnic Birnin Kebbi",
  "Waziri Umaru Federal Polytechnic (NCE AWARDING)",
  "Wellspring University",
  "Wesley University Of Science And Technology",
  "West Africa Theological Seminary, Ipaja, Lagos",
  "Western Delta University",
  "Westland University",
  "Wolex Polytechnic",
  "World Harvest Bible College and Seminary, Calabar",
  "Yaba College of Technology",
  "Yaba College of Technology (Affiliated to University of Nigeria Nsukka)",
  "Yefmadec Institute of Science and Technology, Mosogar",
  "Yewa Central College Of Education",
  "Yobe State College of Agriculture",
  "Yobe State University",
  "Yusuf Bala Usman College Of Legal And General Studies",
  "Yusuf Maitama Sule University Kano",
  "Zamfara State University, Talata Mafara",
  "Zamfara State College of Arts and Science",
  "Others"
];

export const INSTITUTION_TYPES = [
    "UNIVERSITIES AND OTHER DEGREE-AWARDING INSTITUTIONS",
    "COLLEGES OF EDUCATION",
    "POLYTECHNICS AND MONOTECHNICS",
    "INNOVATION ENTERPRISE INSTITUTIONS"
];

export const CATEGORIZED_INSTITUTIONS: Record<string, string[]> = {
    "UNIVERSITIES AND OTHER DEGREE-AWARDING INSTITUTIONS": [],
    "COLLEGES OF EDUCATION": [],
    "POLYTECHNICS AND MONOTECHNICS": [],
    "INNOVATION ENTERPRISE INSTITUTIONS": []
};

RAW_INSTITUTIONS.forEach(inst => {
    const lower = inst.toLowerCase();
    if (lower.includes('university') || lower.includes('degree')) {
         CATEGORIZED_INSTITUTIONS["UNIVERSITIES AND OTHER DEGREE-AWARDING INSTITUTIONS"].push(inst);
    } else if (lower.includes('college of education') || lower.includes('nce')) {
         CATEGORIZED_INSTITUTIONS["COLLEGES OF EDUCATION"].push(inst);
    } else if (lower.includes('polytechnic') || lower.includes('college of tech') || lower.includes('college of agric') || lower.includes('college of health') || lower.includes('school of') || lower.includes('monotechnic')) {
         CATEGORIZED_INSTITUTIONS["POLYTECHNICS AND MONOTECHNICS"].push(inst);
    } else {
         CATEGORIZED_INSTITUTIONS["INNOVATION ENTERPRISE INSTITUTIONS"].push(inst);
    }
});

// Sort them
Object.keys(CATEGORIZED_INSTITUTIONS).forEach(key => {
    CATEGORIZED_INSTITUTIONS[key].sort();
});