export const FACULTIES = [
  {
    name: "Administration",
    courses: [
      "Accountancy / Accounting",
      "Actuarial Science",
      "Banking and Finance",
      "Business Administration",
      "Business Management",
      "Cooperative Economics and Management",
      "Human Resources Management",
      "Industrial Relations and Personnel Management",
      "Insurance",
      "International Relations",
      "Local Government Studies",
      "Marketing",
      "Office Technology and Management",
      "Public Administration",
      "Secretarial Administration",
      "Taxation"
    ]
  },
  {
    name: "Agriculture",
    courses: [
      "Agricultural Economics",
      "Agricultural Extension and Rural Development",
      "Agriculture",
      "Agronomy",
      "Animal Production and Health Services",
      "Animal Science",
      "Crop Production",
      "Crop Science",
      "Fisheries",
      "Food Science and Technology",
      "Forestry and Wildlife Management",
      "Home Science and Management",
      "Hotel Management and Tourism",
      "Soil Science"
    ]
  },
  {
    name: "Arts / Humanities",
    courses: [
      "African Languages and Literature",
      "Arabic Studies",
      "Archaeology",
      "Christian Religious Studies",
      "Creative Arts",
      "English and International Studies",
      "English Language",
      "Fine and Applied Arts",
      "French",
      "Hausa",
      "History and Diplomatic Studies",
      "History and International Studies",
      "Igbo",
      "Islamic Studies",
      "Linguistics",
      "Literature in English",
      "Music",
      "Performing Arts",
      "Philosophy",
      "Religious Studies",
      "Theatre Arts",
      "Yoruba"
    ]
  },
  {
    name: "Education",
    courses: [
      "Adult Education",
      "Agricultural Science and Education",
      "Business Education",
      "Counselor Education",
      "Early Childhood Education",
      "Education & Arabic",
      "Education & Biology",
      "Education & Chemistry",
      "Education & Christian Religious Studies",
      "Education & Economics",
      "Education & English Language",
      "Education & French",
      "Education & Geography",
      "Education & History",
      "Education & Islamic Studies",
      "Education & Mathematics",
      "Education & Physics",
      "Education & Political Science",
      "Education & Social Studies",
      "Educational Administration",
      "Educational Foundations",
      "Educational Management",
      "Guidance and Counseling",
      "Human Kinetics and Health Education",
      "Library and Information Science",
      "Primary Education Studies",
      "Special Education",
      "Teacher Education Science"
    ]
  },
  {
    name: "Engineering / Environmental / Technology",
    courses: [
      "Agricultural Engineering",
      "Architecture",
      "Building Technology",
      "Chemical Engineering",
      "Civil Engineering",
      "Computer Engineering",
      "Electrical / Electronics Engineering",
      "Environmental Management",
      "Estate Management",
      "Food Engineering",
      "Industrial and Production Engineering",
      "Land Surveying",
      "Marine Engineering",
      "Mechanical Engineering",
      "Mechatronics Engineering",
      "Metallurgical and Materials Engineering",
      "Petroleum Engineering",
      "Quantity Surveying",
      "Structural Engineering",
      "Surveying and Geoinformatics",
      "Urban and Regional Planning",
      "Water Resources and Environmental Engineering"
    ]
  },
  {
    name: "Law",
    courses: [
      "Civil Law",
      "Common Law",
      "Criminology and Security Studies",
      "International Law and Jurisprudence",
      "Islamic / Sharia Law",
      "Law",
      "Private and Islamic Law",
      "Public and International Law"
    ]
  },
  {
    name: "Medical / Pharmaceutical Health Science",
    courses: [
      "Anatomy",
      "Biomedical Technology",
      "Dentistry and Dental Surgery",
      "Human Nutrition and Dietetics",
      "Medical Laboratory Science",
      "Medical Rehabilitation",
      "Medicine and Surgery",
      "Nursing / Nursing Science",
      "Optometry",
      "Pharmacy",
      "Physiology",
      "Physiotherapy",
      "Public Health",
      "Radiography",
      "Veterinary Medicine"
    ]
  },
  {
    name: "Sciences",
    courses: [
      "Applied Geophysics",
      "Biochemistry",
      "Biology",
      "Biotechnology",
      "Botany",
      "Chemistry",
      "Computer Science",
      "Cyber Security",
      "Geology",
      "Industrial Chemistry",
      "Industrial Mathematics",
      "Industrial Physics",
      "Information Technology",
      "Mathematics",
      "Microbiology",
      "Physics",
      "Physics with Electronics",
      "Plant Science and Biotechnology",
      "Software Engineering",
      "Statistics",
      "Telecommunication Science",
      "Zoology"
    ]
  },
  {
    name: "Social Management Science",
    courses: [
      "Accounting",
      "Banking and Finance",
      "Business Management",
      "Criminology",
      "Economics",
      "Entrepreneurship",
      "Geography and Regional Planning",
      "Mass Communication",
      "Peace and Conflict Resolution",
      "Political Science",
      "Psychology",
      "Public Administration",
      "Sociology",
      "Transport Management"
    ]
  }
];
