export const INSTITUTION_TYPES = [
    "UNIVERSITIES AND OTHER DEGREE-AWARDING INSTITUTIONS",
    "COLLEGES OF EDUCATION",
    "POLYTECHNICS AND MONOTECHNICS",
    "INNOVATION ENTERPRISE INSTITUTIONS"
];

export const CATEGORIZED_INSTITUTIONS: Record<string, string[]> = {
    "UNIVERSITIES AND OTHER DEGREE-AWARDING INSTITUTIONS": [
        "Abia State University, Uturu",
        "Abubakar Tafawa Balewa University, Bauchi",
        "Achievers University, Owo",
        "Adamawa State University, Mubi",
        "Adekunle Ajasin University, Akungba-Akoko",
        "Adeleke University, Ede",
        "Afe Babalola University, Ado-Ekiti",
        "African University of Science and Technology, Abuja",
        "Ahmadu Bello University, Zaria",
        "Ajayi Crowther University, Oyo",
        "Akwa Ibom State University, Ikot-Akpaden",
        "Alex Ekwueme Federal University, Ndufu-Alike",
        "Al-Hikmah University, Ilorin",
        "Al-Qalam University, Katsina",
        "Ambrose Alli University, Ekpoma",
        "American University of Nigeria, Yola",
        "Anchor University, Lagos",
        "Arthur Jarvis University, Akpabuyo",
        "Atiba University, Oyo",
        "Augustine University, Ilara",
        "Babcock University, Ilishan-Remo",
        "Bamidele Olumilua University of Education, Science and Technology, Ikere-Ekiti",
        "Bauchi State University, Gadau",
        "Bayero University, Kano",
        "Baze University, Abuja",
        "Bell University of Technology, Ota",
        "Benson Idahosa University, Benin City",
        "Benue State University, Makurdi",
        "Bingham University, Karu",
        "Borno State University, Maiduguri",
        "Bowen University, Iwo",
        "Caleb University, Imota",
        "Caritas University, Amorji-Nike",
        "Chrisland University, Owode",
        "Christopher University, Mowe",
        "Chukwuemeka Odumegwu Ojukwu University, Uli",
        "Clifford University, Owerrinta",
        "Coal City University, Enugu",
        "Covenant University, Ota",
        "Crawford University, Igbesa",
        "Crescent University, Abeokuta",
        "Cross River University of Technology, Calabar",
        "Crown Hill University, Eiyenkorin",
        "Delta State University, Abraka",
        "Dominican University, Ibadan",
        "Ebonyi State University, Abakaliki",
        "Edo State University, Uzairue",
        "Edwin Clark University, Kiagbodo",
        "Ekiti State University, Ado-Ekiti",
        "Eko University of Medicine and Health Sciences, Ijanikin",
        "Elizade University, Ilara-Mokin",
        "Enugu State University of Science and Technology, Enugu",
        "Evangel University, Akaeze",
        "Federal University of Agriculture, Abeokuta",
        "Federal University of Petroleum Resources, Effurun",
        "Federal University of Technology, Akure",
        "Federal University of Technology, Minna",
        "Federal University of Technology, Owerri",
        "Federal University, Birnin Kebbi",
        "Federal University, Dutse",
        "Federal University, Dutsin-Ma",
        "Federal University, Gashua",
        "Federal University, Gusau",
        "Federal University, Kashere",
        "Federal University, Lafia",
        "Federal University, Lokoja",
        "Federal University, Otuoke",
        "Federal University, Oye-Ekiti",
        "Federal University, Wukari",
        "Fountain University, Osogbo",
        "Godfrey Okoye University, Ugwuomu-Nike",
        "Gombe State University, Gombe",
        "Gregory University, Uturu",
        "Hallmark University, Ijebu-Itele",
        "Hezekiah University, Umudi",
        "Ibrahim Badamasi Babangida University, Lapai",
        "Igbinedion University, Okada",
        "Ignatius Ajuru University of Education, Port Harcourt",
        "Imo State University, Owerri",
        "Joseph Ayo Babalola University, Ikeji-Arakeji",
        "Kaduna State University, Kaduna",
        "Kano University of Science and Technology, Wudil",
        "Kebbi State University of Science and Technology, Aliero",
        "Kings University, Ode-Omu",
        "Kogi State University, Anyigba",
        "Kola Daisi University, Ibadan",
        "Kwara State University, Malete",
        "Kwararafa University, Wukari",
        "Ladoke Akintola University of Technology, Ogbomoso",
        "Lagos State University, Ojo",
        "Landmark University, Omu-Aran",
        "Lead City University, Ibadan",
        "Legacy University, Okija",
        "Madonna University, Elele",
        "McPherson University, Seriki Sotayo",
        "Michael and Cecilia Ibru University, Agbarha-Otor",
        "Michael Okpara University of Agriculture, Umudike",
        "Modibbo Adama University of Technology, Yola",
        "Mountain Top University, Makogi Oba",
        "Nasarawa State University, Keffi",
        "National Open University of Nigeria",
        "Niger Delta University, Wilberforce Island",
        "Nile University of Nigeria, Abuja",
        "Nnamdi Azikiwe University, Awka",
        "Novena University, Ogume",
        "Obafemi Awolowo University, Ile-Ife",
        "Obong University, Obong Ntak",
        "Oduduwa University, Ipetumodu",
        "Olabisi Onabanjo University, Ago-Iwoye",
        "Ondo State University of Science and Technology, Okitipupa",
        "Osun State University, Osogbo",
        "Pan-Atlantic University, Lagos",
        "Paul University, Awka",
        "Plateau State University, Bokkos",
        "Polaaku University of Science and Technology",
        "Precious Cornerstone University, Ibadan",
        "Redeemer's University, Ede",
        "Renaissance University, Ugbawka",
        "Rhema University, Aba",
        "Ritman University, Ikot Ekpene",
        "Rivers State University, Port Harcourt",
        "Salem University, Lokoja",
        "Samuel Adegboyega University, Ogwa",
        "Skyline University Nigeria, Kano",
        "Sokoto State University, Sokoto",
        "Southwestern University, Okun-Owa",
        "Spiritan University, Nneochi",
        "Summit University, Offa",
        "Tai Solarin University of Education, Ijagun",
        "Tansian University, Umunya",
        "Taraba State University, Jalingo",
        "The Technical University, Ibadan",
        "Umaru Musa Yar'adua University, Katsina",
        "University of Abuja, Abuja",
        "University of Africa, Toru-Orua",
        "University of Agriculture and Environmental Sciences, Umuagwo",
        "University of Benin, Benin City",
        "University of Calabar, Calabar",
        "University of Ibadan, Ibadan",
        "University of Ilorin, Ilorin",
        "University of Jos, Jos",
        "University of Lagos, Lagos",
        "University of Maiduguri, Maiduguri",
        "University of Medical Sciences, Ondo",
        "University of Nigeria, Nsukka",
        "University of Port Harcourt, Port Harcourt",
        "University of Uyo, Uyo",
        "Usman Danfodio University, Sokoto",
        "Veritas University, Abuja",
        "Wellspring University, Benin City",
        "Wesley University, Ondo",
        "Western Delta University, Oghara",
        "Yobe State University, Damaturu",
        "Yusuf Maitama Sule University, Kano",
        "Zamfara State University, Talata Mafara"
    ],
    "COLLEGES OF EDUCATION": [
        "Adeyemi College of Education, Ondo",
        "African Thinkers Community of Inquiry College of Education, Enugu",
        "Akwa Ibom State College of Education, Afaha-Nsit",
        "Alvan Ikoku Federal College of Education, Owerri",
        "Aminu Kano College of Education, Kano",
        "Angel Michel College of Education, Makurdi",
        "Ansar-Ud-Deen College of Education, Isolo",
        "College of Education, Agbor",
        "College of Education, Akwanga",
        "College of Education, Ankpa",
        "College of Education, Azare",
        "College of Education, Ekiadolor-Benin",
        "College of Education, Gindiri",
        "College of Education, Hong",
        "College of Education, Ikere-Ekiti",
        "College of Education, Katsina-Ala",
        "College of Education, Lanlate",
        "College of Education, Minna",
        "College of Education, Oju",
        "College of Education, Warri",
        "College of Education, Zing",
        "Cornerstone College of Education, Lagos",
        "Cross River State College of Education, Akamkpa",
        "Delar College of Education, Ibadan",
        "Delta State College of Physical Education, Mosogar",
        "Diamond College of Education, Aba",
        "Ebonyi State College of Education, Ikwo",
        "Emmanuel Alayande College of Education, Oyo",
        "Federal College of Education (Special), Oyo",
        "Federal College of Education (Technical), Akoka",
        "Federal College of Education (Technical), Asaba",
        "Federal College of Education (Technical), Bichi",
        "Federal College of Education (Technical), Gombe",
        "Federal College of Education (Technical), Gusau",
        "Federal College of Education (Technical), Omoku",
        "Federal College of Education (Technical), Potiskum",
        "Federal College of Education (Technical), Umunze",
        "Federal College of Education, Abeokuta",
        "Federal College of Education, Eha-Amufu",
        "Federal College of Education, Kano",
        "Federal College of Education, Katsina",
        "Federal College of Education, Kontagora",
        "Federal College of Education, Obudu",
        "Federal College of Education, Okene",
        "Federal College of Education, Pankshin",
        "Federal College of Education, Yola",
        "Federal College of Education, Zaria",
        "FCT College of Education, Zuba",
        "Jigawa State College of Education, Gumel",
        "Kaduna State College of Education, Gidan Waya",
        "Kano State College of Education, Kano",
        "Kashim Ibrahim College of Education, Maiduguri",
        "Katsina State College of Education, Katsina",
        "Kebbi State College of Education, Argungu",
        "Kinsey College of Education, Ilorin",
        "Kogi State College of Education, Ankpa",
        "Kwara State College of Education, Ilorin",
        "Kwara State College of Education, Oro",
        "Lagos State College of Primary Education, Noforija",
        "Michael Otedola College of Primary Education, Noforija",
        "Muftau Lanihun College of Education, Ibadan",
        "Nasarawa State College of Education, Akwanga",
        "Niger State College of Education, Minna",
        "Nwafor Orizu College of Education, Nsugbe",
        "Ogun State College of Education, Ijebu-Ode",
        "Osun State College of Education, Ila-Orangun",
        "Osun State College of Education, Ilesa",
        "Peaceland College of Education, Enugu",
        "Plateau State College of Education, Gindiri",
        "Rivers State College of Education, Port Harcourt",
        "Saadatu Rimi College of Education, Kumbotso",
        "Shehu Shagari College of Education, Sokoto",
        "St. Augustine College of Education, Akoka",
        "Tai Solarin College of Education, Omu-Ijebu",
        "Umar Ibn Ibrahim El-Kanemi College of Education, Bama",
        "Zamfara State College of Education, Maru"
    ],
    "POLYTECHNICS AND MONOTECHNICS": [
        "Abdu Gusau Polytechnic, Talata Mafara",
        "Abia State Polytechnic, Aba",
        "Abraham Adesanya Polytechnic, Ijebu-Igbo",
        "Abubakar Tatari Ali Polytechnic, Bauchi",
        "Adamawa State Polytechnic, Yola",
        "Akanu Ibiam Federal Polytechnic, Unwana",
        "Akwa Ibom State Polytechnic, Ikot Osurua",
        "Alovera Polytechnic, Ota",
        "Auchi Polytechnic, Auchi",
        "Benue State Polytechnic, Ugbokolo",
        "Binyaminu Usman Polytechnic, Hadejia",
        "Bolmor Polytechnic, Ibadan",
        "Delta State Polytechnic, Ogwashi-Uku",
        "Delta State Polytechnic, Otefe-Oghara",
        "Delta State Polytechnic, Ozoro",
        "Dorben Polytechnic, Abuja",
        "Eastern Polytechnic, Port Harcourt",
        "Edo State Institute of Technology and Management, Usen",
        "Federal Polytechnic, Ado-Ekiti",
        "Federal Polytechnic, Bali",
        "Federal Polytechnic, Bauchi",
        "Federal Polytechnic, Bida",
        "Federal Polytechnic, Damaturu",
        "Federal Polytechnic, Ede",
        "Federal Polytechnic, Ekowe",
        "Federal Polytechnic, Idah",
        "Federal Polytechnic, Ilaro",
        "Federal Polytechnic, Ile-Oluji",
        "Federal Polytechnic, Kaura Namoda",
        "Federal Polytechnic, Mubi",
        "Federal Polytechnic, Nasarawa",
        "Federal Polytechnic, Nekede",
        "Federal Polytechnic, Offa",
        "Federal Polytechnic, Oko",
        "Federal Polytechnic, Ukana",
        "Fidei Polytechnic, Gboko",
        "Gateway Polytechnic, Saapade",
        "Grace Polytechnic, Surulere",
        "Hassan Usman Katsina Polytechnic, Katsina",
        "Heritage Polytechnic, Eket",
        "Hussaini Adamu Federal Polytechnic, Kazaure",
        "Ibarapa Polytechnic, Eruwa",
        "Igbajo Polytechnic, Igbajo",
        "Institute of Management and Technology, Enugu",
        "Interlink Polytechnic, Ijebu-Jesa",
        "Jigawa State Polytechnic, Dutse",
        "Kaduna Polytechnic, Kaduna",
        "Kano State Polytechnic, Kano",
        "Kings Polytechnic, Ubiaja",
        "Kogi State Polytechnic, Lokoja",
        "Kwara State Polytechnic, Ilorin",
        "Lagos City Polytechnic, Ikeja",
        "Lagos State Polytechnic, Ikorodu",
        "Light House Polytechnic, Evbuobanosa",
        "Mai Idris Alooma Polytechnic, Geidam",
        "Moshood Abiola Polytechnic, Abeokuta",
        "Nasarawa State Polytechnic, Lafia",
        "Niger State Polytechnic, Zungeru",
        "Nuhu Bamalli Polytechnic, Zaria",
        "Ogun State Institute of Technology, Igbesa",
        "Oke-Ogun Polytechnic, Saki",
        "Osun State Polytechnic, Iree",
        "Plateau State Polytechnic, Barkin Ladi",
        "Polytechnic of Sokoto State, Sokoto",
        "Ramat Polytechnic, Maiduguri",
        "Rivers State Polytechnic, Bori",
        "Ronik Polytechnic, Ejigbo",
        "Rufus Giwa Polytechnic, Owo",
        "Shaka Polytechnic, Benin City",
        "Temple Gate Polytechnic, Aba",
        "The Polytechnic, Ibadan",
        "Tower Polytechnic, Ibadan",
        "Waziri Umaru Federal Polytechnic, Birnin Kebbi",
        "Wolex Polytechnic, Iyana Ipaja",
        "Yaba College of Technology, Yaba",
        "Zamfara State Polytechnic, Talata Mafara"
    ],
    "INNOVATION ENTERPRISE INSTITUTIONS": [
        "Afrihub ICT Institute, Abuja",
        "Ambassador College of Management and Technology, Port Harcourt",
        "Buckingham Academy of Management and Technology, Ogidi",
        "Center for Creative Arts Education, Port Harcourt",
        "City Gate Institute of Innovation and Technology, Ibadan",
        "Complete Computers and Technology Institute, Benin City",
        "Dalewares Institute of Technology, Lagos",
        "Dialogue Computer Institute, Kaduna",
        "Digital Bridge Institute, Abuja",
        "Emdee Shipping and Maritime College, Apapa",
        "Friskel Divinity College, Gariki",
        "Global Maritime Academy, Ogoni",
        "Highland College of Technology and Further Education, Ibadan",
        "Ibadan City Polytechnic, Ibadan",
        "Imfi Academy, Uyo",
        "KarRox Processor, Ogba",
        "Lagos Aviation and Maritime Business Academy, Iba",
        "Lineo School of Media and Design, Lagos",
        "Mario Institute of Hospitality Management and Entrepreneurship Education, Nsukka",
        "Marvel Institute of Management and Technology, Kuchikau",
        "Maurid Institute of Management and Technology, Oron",
        "NIIT Education and Training Centre, Ikeja",
        "Offer Centre Institute of Agriculture, Oluponna",
        "Olawoyin School of Innovative Studies, Ibadan",
        "Pefti Film Institute, Lagos",
        "Prime Innovation Institute of Technology, Ajah",
        "Risk Control Academy, Lagos",
        "Rolof Computer Academy, Warri",
        "School of Banking Honours, Lagos",
        "Southern Nigerian Institute of Innovative Technology, Owerri",
        "Stars Maritime Academy, Iju",
        "Total Human Capital Development Institute, Lagos",
        "Tower Polytechnic, Ibadan",
        "Unival Institute of Technology, Benin City",
        "Upskill Digital Institute, Lagos",
        "Yenagoa Enterprise School, Yenagoa"
    ]
};
