export const ALL_SUBJECTS = [
    'Agriculture Science',
    'Arabic',
    'Art',
    'Biology',
    'Chemistry',
    'Christian Religious Studies',
    'Commerce',
    'Computer Studies',
    'Economics',
    'French',
    'Geography',
    'Government',
    'Hausa',
    'History',
    'Home Economics',
    'Igbo',
    'Islamic Studies',
    'Literature-In-English',
    'Mathematics',
    'Music',
    'Physics',
    'Physical and Health Education',
    'Principles of Accounts',
    'Use of English',
    'Yoruba'
];
